### ISSUE TITLE
Fix Discord Widget scaling on contact page

### ISSUE THREAD

**Issue by Pips801** [801labs/801labs.org#7]
Widget is too narrow, needs to be expanded.
![image](https://user-images.githubusercontent.com/5651603/140179031-61e3fe5f-7990-4a8e-87c7-038828644914.png)

**Comment by ninnypants** [comment]
@Pips801 shouldn't this be closed?

**Comment by AdmiralPotato** [comment]
> @Pips801 shouldn't this be closed?

It looks like it's already done to me. Closing.
Thanks @ninnypants
